import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "./globals.css";
import { createTheme, MantineProvider } from "@mantine/core";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const theme = createTheme({});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es">
			<head>
				{/* Fonts */}
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="anonymous"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body>
				<MantineProvider theme={theme}>{children}</MantineProvider>
			</body>
		</html>
	);
}
